fix of type cast error
System.TypeInitializationException: The type initializer for 'PlantMAT.Core.PublicVSCode' threw an exception. ---> System.ArgumentException: Argument 'Expression' cannot be converted to type 'DefaultString'.